from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List


SCRIPT_DIR = Path(__file__).resolve().parent
DYNAMIC_DIR = SCRIPT_DIR / "rules" / "dynamic"

RULE_FILES: Dict[str, Dict[str, object]] = {
    "non_llm_unlabeled": {
        "path": DYNAMIC_DIR / "non_llm" / "unlabeled_rules.json",
        "payload": {
            "rules": [],
            "note": "Cleared. Generated by non_llm_unlabeled training in scripts/run_experiments.py.",
        },
    },
    "non_llm_labeled": {
        "path": DYNAMIC_DIR / "non_llm" / "labeled_rules.json",
        "payload": {
            "rules": [],
            "note": "Cleared. Generated by non_llm_labeled training in scripts/run_experiments.py.",
        },
    },
    "llm_no_train": {
        "path": DYNAMIC_DIR / "llm" / "no_train_rules.json",
        "payload": {
            "rules": [],
            "final_answer_config": {},
            "proposed_features": [],
            "note": "Cleared. Generated by llm_no_train training in scripts/run_experiments.py.",
        },
    },
    "llm_unlabeled": {
        "path": DYNAMIC_DIR / "llm" / "unlabeled_rules.json",
        "payload": {
            "rules": [],
            "final_answer_config": {},
            "proposed_features": [],
            "note": "Cleared. Generated by llm_unlabeled training in scripts/run_experiments.py.",
        },
    },
    "llm_labeled": {
        "path": DYNAMIC_DIR / "llm" / "labeled_rules.json",
        "payload": {
            "rules": [],
            "final_answer_config": {},
            "proposed_features": [],
            "note": "Cleared. Generated by llm_labeled training in scripts/run_experiments.py.",
        },
    },
}


def _selected_keys(methods: str) -> List[str]:
    if methods == "all":
        return list(RULE_FILES)
    aliases = {
        "non_llm": ["non_llm_unlabeled", "non_llm_labeled"],
        "llm": ["llm_no_train", "llm_unlabeled", "llm_labeled"],
    }
    selected: List[str] = []
    for raw in methods.split(","):
        item = raw.strip()
        if not item:
            continue
        keys = aliases.get(item, [item])
        for key in keys:
            if key not in RULE_FILES:
                raise ValueError(f"Unknown dynamic rule target: {key}")
            if key not in selected:
                selected.append(key)
    return selected


def clear_dynamic_rules(methods: str, *, dry_run: bool = False) -> List[Path]:
    cleared: List[Path] = []
    for key in _selected_keys(methods):
        entry = RULE_FILES[key]
        path = Path(entry["path"])
        payload = entry["payload"]
        if not dry_run:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        cleared.append(path)
    return cleared


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Clear generated dynamic rule files by resetting them to empty rule payloads."
    )
    parser.add_argument(
        "--methods",
        default="all",
        help=(
            "Comma-separated targets to clear. Use all, non_llm, llm, or exact names: "
            "non_llm_unlabeled, non_llm_labeled, llm_no_train, llm_unlabeled, llm_labeled."
        ),
    )
    parser.add_argument("--dry-run", action="store_true", help="Show files that would be cleared without writing.")
    return parser


def main() -> None:
    args = build_parser().parse_args()
    paths = clear_dynamic_rules(args.methods, dry_run=args.dry_run)
    action = "Would clear" if args.dry_run else "Cleared"
    for path in paths:
        print(f"{action}: {path}")


if __name__ == "__main__":
    main()
