from __future__ import annotations

import json
import statistics
from pathlib import Path
from typing import Any, Dict, Iterable, List

from features import FinalAnswerConfig, extract_features
from trace_io import TraceRecord, records_with_labels


NUMERIC_BAD_FEATURES = [
    "step_count",
    "repeated_action_count",
    "max_consecutive_same_action",
    "error_count",
    "empty_result_count",
    "empty_result_ratio",
]


def _percentile(values: List[float], q: float) -> float:
    if not values:
        return 0.0
    values = sorted(values)
    if len(values) == 1:
        return values[0]
    position = (len(values) - 1) * q
    lower = int(position)
    upper = min(lower + 1, len(values) - 1)
    fraction = position - lower
    return values[lower] * (1 - fraction) + values[upper] * fraction


def _write_rules(path: str | Path, rules: List[Dict[str, Any]]) -> Path:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "rules": rules,
        "note": "Generated by scripts/rule_generation.py. Deterministic experiment rules; no manual review is required before evaluation.",
    }
    with output.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)
        handle.write("\n")
    return output


def generate_unlabeled_rules(
    records: Iterable[TraceRecord],
    output_path: str | Path,
    final_answer_config: FinalAnswerConfig | None = None,
) -> List[Dict[str, Any]]:
    feature_rows = [extract_features(record, final_answer_config) for record in records]
    rules: List[Dict[str, Any]] = []
    for feature in NUMERIC_BAD_FEATURES:
        values = [float(row.get(feature, 0.0)) for row in feature_rows]
        threshold = _percentile(values, 0.90)
        if feature.endswith("_ratio"):
            threshold = max(0.50, round(threshold, 2))
        else:
            threshold = max(1.0, round(threshold))
        if threshold <= 0:
            continue
        rules.append(
            {
                "id": f"unlabeled_high_{feature}",
                "layer": "unlabeled",
                "label": "badcase",
                "weight": 0.25,
                "description": f"{feature} is high relative to the unlabeled trace cohort.",
                "all": [{"feature": feature, "op": ">=", "value": threshold}],
            }
        )

    if any(row.get("has_final_answer") for row in feature_rows):
        rules.append(
            {
                "id": "unlabeled_missing_final_when_cohort_has_finals",
                "layer": "unlabeled",
                "label": "badcase",
                "weight": 0.35,
                "description": "Most comparable traces expose a final answer, but this one does not.",
                "all": [
                    {"feature": "final_answer_evidence_enabled", "op": "==", "value": True},
                    {"feature": "has_final_answer", "op": "==", "value": False},
                ],
            }
        )
    _write_rules(output_path, rules)
    return rules


def _mean(rows: List[Dict[str, Any]], feature: str) -> float:
    values = [float(row.get(feature, 0.0)) for row in rows]
    return statistics.fmean(values) if values else 0.0


def generate_labeled_rules(
    records: Iterable[TraceRecord],
    output_path: str | Path,
    final_answer_config: FinalAnswerConfig | None = None,
) -> List[Dict[str, Any]]:
    labeled = records_with_labels(records)
    rows = [(record.label, extract_features(record, final_answer_config)) for record in labeled]
    good_rows = [features for label, features in rows if label == "goodcase"]
    bad_rows = [features for label, features in rows if label == "badcase"]
    if not good_rows or not bad_rows:
        _write_rules(output_path, [])
        return []

    rules: List[Dict[str, Any]] = []
    for feature in NUMERIC_BAD_FEATURES:
        bad_mean = _mean(bad_rows, feature)
        good_mean = _mean(good_rows, feature)
        if bad_mean <= good_mean:
            continue
        gap = bad_mean - good_mean
        if feature.endswith("_ratio") and gap < 0.10:
            continue
        if not feature.endswith("_ratio") and gap < 0.75:
            continue
        threshold = (bad_mean + good_mean) / 2.0
        threshold = round(threshold, 2) if feature.endswith("_ratio") else max(1, round(threshold))
        rules.append(
            {
                "id": f"labeled_bad_high_{feature}",
                "layer": "labeled",
                "label": "badcase",
                "weight": 0.35,
                "description": f"Labeled badcase train traces have higher {feature} than goodcase traces.",
                "all": [{"feature": feature, "op": ">=", "value": threshold}],
            }
        )

    good_final_rate = sum(1 for row in good_rows if row.get("has_final_answer")) / len(good_rows)
    bad_final_rate = sum(1 for row in bad_rows if row.get("has_final_answer")) / len(bad_rows)
    if good_final_rate - bad_final_rate >= 0.25:
        rules.append(
            {
                "id": "labeled_missing_final_answer",
                "layer": "labeled",
                "label": "badcase",
                "weight": 0.45,
                "description": "Missing final answer is more common in labeled badcase train traces.",
                "all": [
                    {"feature": "final_answer_evidence_enabled", "op": "==", "value": True},
                    {"feature": "has_final_answer", "op": "==", "value": False},
                ],
            }
        )
        rules.append(
            {
                "id": "labeled_has_final_answer_support",
                "layer": "labeled",
                "label": "goodcase",
                "weight": 0.25,
                "description": "Final answer presence is more common in labeled goodcase train traces.",
                "all": [
                    {"feature": "final_answer_evidence_enabled", "op": "==", "value": True},
                    {"feature": "has_final_answer", "op": "==", "value": True},
                ],
            }
        )

    _write_rules(output_path, rules)
    return rules
