from __future__ import annotations

import json
import re
import statistics
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List

from features import FinalAnswerConfig, extract_features
from trace_io import TraceRecord, records_with_labels


NUMERIC_BAD_FEATURES = [
    "step_count",
    "repeated_action_count",
    "max_consecutive_same_action",
    "error_count",
    "empty_result_count",
    "empty_result_ratio",
]
MAX_DYNAMIC_FIELD_RULES = 30
MAX_DYNAMIC_FIELD_VALUE_CHARS = 80


def _percentile(values: List[float], q: float) -> float:
    if not values:
        return 0.0
    values = sorted(values)
    if len(values) == 1:
        return values[0]
    position = (len(values) - 1) * q
    lower = int(position)
    upper = min(lower + 1, len(values) - 1)
    fraction = position - lower
    return values[lower] * (1 - fraction) + values[upper] * fraction


def _write_rules(path: str | Path, rules: List[Dict[str, Any]]) -> Path:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "rules": rules,
        "note": "Generated by scripts/rule_generation.py. Deterministic experiment rules; no manual review is required before evaluation.",
    }
    with output.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)
        handle.write("\n")
    return output


def _safe_rule_id(text: str, max_chars: int = 80) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9_]+", "_", text).strip("_").lower()
    return (cleaned or "field")[:max_chars]


def _fixed_feature_group(feature: str) -> str:
    if "result" in feature:
        return "result_quality"
    if "error" in feature:
        return "error_signal"
    if "repeated" in feature or "consecutive" in feature:
        return "loop_repetition"
    return "structure"


def _dynamic_paths(rows: List[Dict[str, Any]]) -> List[str]:
    paths: set[str] = set()
    for row in rows:
        for feature in row:
            if feature.startswith("field_exists:"):
                paths.add(feature.split(":", 1)[1])
    return sorted(paths)


def _presence_rate(rows: List[Dict[str, Any]], path: str) -> float:
    if not rows:
        return 0.0
    return sum(1 for row in rows if row.get(f"field_exists:{path}") is True) / len(rows)


def _nonempty_rate(rows: List[Dict[str, Any]], path: str) -> float:
    if not rows:
        return 0.0
    values = [float(row.get(f"field_nonempty_ratio:{path}", 0.0)) for row in rows]
    return statistics.fmean(values) if values else 0.0


def _short_text_values(rows: List[Dict[str, Any]], path: str) -> Counter[str]:
    values: Counter[str] = Counter()
    feature = f"field_text:{path}"
    for row in rows:
        raw = str(row.get(feature, "")).strip()
        if not raw or "\n" in raw:
            continue
        if len(raw) <= MAX_DYNAMIC_FIELD_VALUE_CHARS:
            values[raw] += 1
    return values


def _number_mean(row: Dict[str, Any], path: str) -> float | None:
    value = row.get(f"field_number_mean:{path}")
    if value is None:
        value = row.get(f"field_number:{path}")
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _mean_optional(values: List[float | None]) -> float | None:
    present = [value for value in values if value is not None]
    if not present:
        return None
    return statistics.fmean(present)


def _dynamic_unlabeled_field_rules(feature_rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    if len(feature_rows) < 3:
        return []
    rules: List[Dict[str, Any]] = []
    for path in _dynamic_paths(feature_rows):
        if len(rules) >= MAX_DYNAMIC_FIELD_RULES:
            break
        presence = _presence_rate(feature_rows, path)
        nonempty = _nonempty_rate(feature_rows, path)
        field_id = _safe_rule_id(path)
        if presence >= 0.80:
            rules.append(
                {
                    "id": f"unlabeled_missing_common_field_{field_id}",
                    "layer": "unlabeled",
                    "component": "unlabeled_field_presence",
                    "feature_group": "dynamic_fields",
                    "source_method": "non_llm_unlabeled",
                    "label": "badcase",
                    "weight": 0.20,
                    "description": f"Field `{path}` is common in unlabeled train traces but missing in this trace.",
                    "all": [{"feature": f"field_exists:{path}", "op": "==", "value": False}],
                }
            )
        if len(rules) >= MAX_DYNAMIC_FIELD_RULES:
            break
        if presence >= 0.80 and nonempty >= 0.80:
            rules.append(
                {
                    "id": f"unlabeled_empty_common_field_{field_id}",
                    "layer": "unlabeled",
                    "component": "unlabeled_field_presence",
                    "feature_group": "dynamic_fields",
                    "source_method": "non_llm_unlabeled",
                    "label": "badcase",
                    "weight": 0.20,
                    "description": f"Field `{path}` is usually non-empty in unlabeled train traces but empty in this trace.",
                    "all": [
                        {"feature": f"field_exists:{path}", "op": "==", "value": True},
                        {"feature": f"field_nonempty_ratio:{path}", "op": "==", "value": 0.0},
                    ],
                }
            )
    return rules


def _dynamic_labeled_field_rules(good_rows: List[Dict[str, Any]], bad_rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    rules: List[Dict[str, Any]] = []
    paths = sorted(set(_dynamic_paths(good_rows)) | set(_dynamic_paths(bad_rows)))
    for path in paths:
        if len(rules) >= MAX_DYNAMIC_FIELD_RULES:
            break
        good_presence = _presence_rate(good_rows, path)
        bad_presence = _presence_rate(bad_rows, path)
        field_id = _safe_rule_id(path)
        if bad_presence - good_presence >= 0.50:
            rules.append(
                    {
                        "id": f"labeled_bad_field_present_{field_id}",
                        "layer": "labeled",
                        "component": "labeled_field_presence",
                        "feature_group": "dynamic_fields",
                        "source_method": "non_llm_labeled",
                        "label": "badcase",
                    "weight": 0.30,
                    "description": f"Field `{path}` appears much more often in labeled badcase train traces.",
                    "all": [{"feature": f"field_exists:{path}", "op": "==", "value": True}],
                }
            )
        elif good_presence - bad_presence >= 0.50:
            rules.append(
                    {
                        "id": f"labeled_good_field_present_{field_id}",
                        "layer": "labeled",
                        "component": "labeled_field_presence",
                        "feature_group": "dynamic_fields",
                        "source_method": "non_llm_labeled",
                        "label": "goodcase",
                    "weight": 0.25,
                    "description": f"Field `{path}` appears much more often in labeled goodcase train traces.",
                    "all": [{"feature": f"field_exists:{path}", "op": "==", "value": True}],
                }
            )
            rules.append(
                    {
                        "id": f"labeled_bad_missing_good_field_{field_id}",
                        "layer": "labeled",
                        "component": "labeled_field_presence",
                        "feature_group": "dynamic_fields",
                        "source_method": "non_llm_labeled",
                        "label": "badcase",
                    "weight": 0.25,
                    "description": f"Field `{path}` is common in goodcase train traces but often absent from badcase traces.",
                    "all": [{"feature": f"field_exists:{path}", "op": "==", "value": False}],
                }
            )

        if len(rules) >= MAX_DYNAMIC_FIELD_RULES:
            break
        bad_values = _short_text_values(bad_rows, path)
        good_values = _short_text_values(good_rows, path)
        for value, bad_count in bad_values.most_common(5):
            bad_rate = bad_count / len(bad_rows)
            good_rate = good_values.get(value, 0) / len(good_rows)
            if bad_rate - good_rate >= 0.50:
                rules.append(
                        {
                            "id": f"labeled_bad_value_{field_id}_{_safe_rule_id(value, 32)}",
                            "layer": "labeled",
                            "component": "labeled_field_value",
                            "feature_group": "dynamic_fields",
                            "source_method": "non_llm_labeled",
                            "label": "badcase",
                        "weight": 0.35,
                        "description": f"Value `{value}` in field `{path}` is much more common in badcase train traces.",
                        "all": [{"feature": f"field_text:{path}", "op": "contains", "value": value}],
                    }
                )
                break
        if len(rules) >= MAX_DYNAMIC_FIELD_RULES:
            break
        for value, good_count in good_values.most_common(5):
            good_rate = good_count / len(good_rows)
            bad_rate = bad_values.get(value, 0) / len(bad_rows)
            if good_rate - bad_rate >= 0.50:
                rules.append(
                        {
                            "id": f"labeled_good_value_{field_id}_{_safe_rule_id(value, 32)}",
                            "layer": "labeled",
                            "component": "labeled_field_value",
                            "feature_group": "dynamic_fields",
                            "source_method": "non_llm_labeled",
                            "label": "goodcase",
                        "weight": 0.30,
                        "description": f"Value `{value}` in field `{path}` is much more common in goodcase train traces.",
                        "all": [{"feature": f"field_text:{path}", "op": "contains", "value": value}],
                    }
                )
                break

        good_mean = _mean_optional([_number_mean(row, path) for row in good_rows])
        bad_mean = _mean_optional([_number_mean(row, path) for row in bad_rows])
        if good_mean is None or bad_mean is None:
            continue
        gap = abs(bad_mean - good_mean)
        if gap < max(1.0, abs(good_mean) * 0.10, abs(bad_mean) * 0.10):
            continue
        threshold = round((good_mean + bad_mean) / 2.0, 4)
        if bad_mean > good_mean:
            rules.append(
                {
                    "id": f"labeled_bad_high_field_number_{field_id}",
                    "layer": "labeled",
                    "component": "labeled_field_numeric",
                    "feature_group": "dynamic_fields",
                    "source_method": "non_llm_labeled",
                    "label": "badcase",
                    "weight": 0.30,
                    "description": f"Numeric field `{path}` is higher in badcase train traces.",
                    "all": [{"feature": f"field_number_mean:{path}", "op": ">=", "value": threshold}],
                }
            )
        else:
            rules.append(
                {
                    "id": f"labeled_good_high_field_number_{field_id}",
                    "layer": "labeled",
                    "component": "labeled_field_numeric",
                    "feature_group": "dynamic_fields",
                    "source_method": "non_llm_labeled",
                    "label": "goodcase",
                    "weight": 0.25,
                    "description": f"Numeric field `{path}` is higher in goodcase train traces.",
                    "all": [{"feature": f"field_number_mean:{path}", "op": ">=", "value": threshold}],
                }
            )
    return rules[:MAX_DYNAMIC_FIELD_RULES]


def generate_unlabeled_rules(
    records: Iterable[TraceRecord],
    output_path: str | Path,
    final_answer_config: FinalAnswerConfig | None = None,
) -> List[Dict[str, Any]]:
    feature_rows = [extract_features(record, final_answer_config) for record in records]
    rules: List[Dict[str, Any]] = []
    for feature in NUMERIC_BAD_FEATURES:
        values = [float(row.get(feature, 0.0)) for row in feature_rows]
        threshold = _percentile(values, 0.90)
        if feature.endswith("_ratio"):
            threshold = max(0.50, round(threshold, 2))
        else:
            threshold = max(1.0, round(threshold))
        if threshold <= 0:
            continue
        rules.append(
            {
                "id": f"unlabeled_high_{feature}",
                "layer": "unlabeled",
                "component": "unlabeled_numeric_quantile",
                "feature_group": _fixed_feature_group(feature),
                "source_method": "non_llm_unlabeled",
                "label": "badcase",
                "weight": 0.25,
                "description": f"{feature} is high relative to the unlabeled trace cohort.",
                "all": [{"feature": feature, "op": ">=", "value": threshold}],
            }
        )

    if any(row.get("has_final_answer") for row in feature_rows):
        rules.append(
            {
                "id": "unlabeled_missing_final_when_cohort_has_finals",
                "layer": "unlabeled",
                "component": "unlabeled_final_answer",
                "feature_group": "final_answer",
                "source_method": "non_llm_unlabeled",
                "label": "badcase",
                "weight": 0.35,
                "description": "Most comparable traces expose a final answer, but this one does not.",
                "all": [
                    {"feature": "final_answer_evidence_enabled", "op": "==", "value": True},
                    {"feature": "has_final_answer", "op": "==", "value": False},
                ],
            }
        )
    rules.extend(_dynamic_unlabeled_field_rules(feature_rows))
    _write_rules(output_path, rules)
    return rules


def _mean(rows: List[Dict[str, Any]], feature: str) -> float:
    values = [float(row.get(feature, 0.0)) for row in rows]
    return statistics.fmean(values) if values else 0.0


def generate_labeled_rules(
    records: Iterable[TraceRecord],
    output_path: str | Path,
    final_answer_config: FinalAnswerConfig | None = None,
) -> List[Dict[str, Any]]:
    labeled = records_with_labels(records)
    rows = [(record.label, extract_features(record, final_answer_config)) for record in labeled]
    good_rows = [features for label, features in rows if label == "goodcase"]
    bad_rows = [features for label, features in rows if label == "badcase"]
    if not good_rows or not bad_rows:
        _write_rules(output_path, [])
        return []

    rules: List[Dict[str, Any]] = []
    for feature in NUMERIC_BAD_FEATURES:
        bad_mean = _mean(bad_rows, feature)
        good_mean = _mean(good_rows, feature)
        if bad_mean <= good_mean:
            continue
        gap = bad_mean - good_mean
        if feature.endswith("_ratio") and gap < 0.10:
            continue
        if not feature.endswith("_ratio") and gap < 0.75:
            continue
        threshold = (bad_mean + good_mean) / 2.0
        threshold = round(threshold, 2) if feature.endswith("_ratio") else max(1, round(threshold))
        rules.append(
            {
                "id": f"labeled_bad_high_{feature}",
                "layer": "labeled",
                "component": "labeled_numeric_diff",
                "feature_group": _fixed_feature_group(feature),
                "source_method": "non_llm_labeled",
                "label": "badcase",
                "weight": 0.35,
                "description": f"Labeled badcase train traces have higher {feature} than goodcase traces.",
                "all": [{"feature": feature, "op": ">=", "value": threshold}],
            }
        )

    good_final_rate = sum(1 for row in good_rows if row.get("has_final_answer")) / len(good_rows)
    bad_final_rate = sum(1 for row in bad_rows if row.get("has_final_answer")) / len(bad_rows)
    if good_final_rate - bad_final_rate >= 0.25:
        rules.append(
            {
                "id": "labeled_missing_final_answer",
                "layer": "labeled",
                "component": "labeled_final_answer_diff",
                "feature_group": "final_answer",
                "source_method": "non_llm_labeled",
                "label": "badcase",
                "weight": 0.45,
                "description": "Missing final answer is more common in labeled badcase train traces.",
                "all": [
                    {"feature": "final_answer_evidence_enabled", "op": "==", "value": True},
                    {"feature": "has_final_answer", "op": "==", "value": False},
                ],
            }
        )
        rules.append(
            {
                "id": "labeled_has_final_answer_support",
                "layer": "labeled",
                "component": "labeled_final_answer_diff",
                "feature_group": "final_answer",
                "source_method": "non_llm_labeled",
                "label": "goodcase",
                "weight": 0.25,
                "description": "Final answer presence is more common in labeled goodcase train traces.",
                "all": [
                    {"feature": "final_answer_evidence_enabled", "op": "==", "value": True},
                    {"feature": "has_final_answer", "op": "==", "value": True},
                ],
            }
        )

    rules.extend(_dynamic_labeled_field_rules(good_rows, bad_rows))
    _write_rules(output_path, rules)
    return rules
