from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List

from features import discover_default_final_answer_config, load_final_answer_config
from llm_rule_prompt import build_prompt_from_records
from run_experiments import (
    DatasetBundle,
    method_training_scenario,
    parse_methods,
    prepare_datasets,
    rules_path_for_method,
)


DEFAULT_LLM_METHODS = "llm_no_train,llm_unlabeled,llm_labeled"


def _ensure_rule_file(path: Path) -> None:
    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(
            {
                "rules": [],
                "final_answer_config": {},
                "proposed_features": [],
                "note": "Fill this file with rules generated by the current Agent from the matching prompt.",
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def _prompt_records(method: str, bundle: DatasetBundle) -> List[Any]:
    scenario = method_training_scenario(method)
    return [] if scenario == "no_train" else bundle.train_records


def _evaluation_command(args: argparse.Namespace, methods: List[str]) -> str:
    parts = [
        "python",
        r".\scripts\run_experiments.py",
        str(args.trace_path),
    ]
    if args.metadata:
        parts.extend(["--metadata", str(args.metadata)])
    if args.train_trace_path:
        parts.extend(["--train-trace-path", str(args.train_trace_path)])
    if args.train_metadata:
        parts.extend(["--train-metadata", str(args.train_metadata)])
    if args.train_split:
        parts.extend(["--train-split", str(args.train_split)])
    if args.eval_split:
        parts.extend(["--eval-split", str(args.eval_split)])
    parts.extend(["--methods", ",".join(methods)])
    parts.extend(["--llm-use-existing-rules"])
    parts.extend(["--output", str(args.report_output)])
    return " ".join(parts)


def prepare_agent_llm_tasks(args: argparse.Namespace) -> Path:
    bundle = prepare_datasets(args)
    methods = parse_methods(args.methods, bundle)
    methods = [method for method in methods if method.startswith("llm_")]
    if not methods:
        raise ValueError("Agent LLM workflow requires at least one llm_* method.")

    output_dir = Path(args.output_dir)
    prompt_dir = output_dir / "agent_llm_prompts"
    prompt_dir.mkdir(parents=True, exist_ok=True)

    final_answer_config = discover_default_final_answer_config(
        bundle.train_records or bundle.all_records,
        load_final_answer_config(args.final_answer_config, args.final_answer_item),
    )

    tasks: List[Dict[str, Any]] = []
    for method in methods:
        scenario = method_training_scenario(method)
        prompt = build_prompt_from_records(
            _prompt_records(method, bundle),
            final_answer_config=final_answer_config,
            training_scenario=scenario,
            max_samples=args.llm_max_samples,
            max_prompt_chars=args.llm_max_prompt_chars,
            max_trace_chars=args.llm_max_trace_chars,
            max_dynamic_fields=args.llm_max_dynamic_fields,
        )
        prompt_path = prompt_dir / f"{method}_prompt.md"
        prompt_path.write_text(prompt + "\n", encoding="utf-8")
        rules_path = rules_path_for_method(method)
        _ensure_rule_file(rules_path)
        tasks.append(
            {
                "method": method,
                "training_scenario": scenario,
                "prompt_path": str(prompt_path),
                "rules_path": str(rules_path),
                "instruction": "Read prompt_path, use the current Agent LLM to produce valid JSON rules, then write them to rules_path.",
            }
        )

    manifest = {
        "workflow": "agent_llm_rule_generation",
        "trace_path": str(args.trace_path),
        "metadata": str(args.metadata) if args.metadata else None,
        "train_source": bundle.train_source,
        "test_source": bundle.test_source,
        "tasks": tasks,
        "evaluation_command": _evaluation_command(args, methods),
        "important": [
            "Do not call scripts/llm_rule_prompt.py::call_llm().",
            "Generate rules with the current Agent's own LLM capability.",
            "After writing all rules_path files, run evaluation_command.",
        ],
    }

    manifest_path = output_dir / "agent_llm_tasks.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    md_path = output_dir / "agent_llm_tasks.md"
    lines = [
        "# Agent LLM Workflow Tasks",
        "",
        "Use the current Agent LLM to generate rules. Do not call `call_llm()`.",
        "",
        f"- Trace path: `{args.trace_path}`",
        f"- Metadata: `{args.metadata}`" if args.metadata else "- Metadata: none",
        f"- Train source: `{bundle.train_source}`",
        f"- Test source: `{bundle.test_source}`",
        "",
        "## Tasks",
        "",
    ]
    for task in tasks:
        lines.extend(
            [
                f"### {task['method']}",
                "",
                f"- Scenario: `{task['training_scenario']}`",
                f"- Read prompt: `{task['prompt_path']}`",
                f"- Write rules: `{task['rules_path']}`",
                "",
            ]
        )
    lines.extend(["## Evaluate", "", "```powershell", manifest["evaluation_command"], "```", ""])
    md_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote Agent LLM task manifest: {manifest_path}")
    print(f"Wrote Agent LLM task guide: {md_path}")
    for task in tasks:
        print(f"{task['method']}: prompt={task['prompt_path']} rules={task['rules_path']}")
    print("After writing rule files, run:")
    print(manifest["evaluation_command"])
    return manifest_path


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Prepare prompts and a task manifest for Agent-driven LLM rule generation."
    )
    parser.add_argument("trace_path", help="Test trace JSON file or directory, unless --eval-split selects a subset.")
    parser.add_argument("--metadata", help="Optional metadata CSV with name,label,source,split columns.")
    parser.add_argument("--train-trace-path", help="Optional separate training trace JSON file or directory.")
    parser.add_argument("--train-metadata", help="Optional training metadata CSV. Defaults to --metadata when omitted.")
    parser.add_argument("--train-split", help="Split value used as training data.")
    parser.add_argument("--eval-split", help="Split value used as test/evaluation data.")
    parser.add_argument("--methods", default=DEFAULT_LLM_METHODS, help="Comma-separated llm_* methods to prepare.")
    parser.add_argument("--output-dir", default="./results", help="Directory for prompts and task manifest.")
    parser.add_argument("--report-output", default="./results/llm_methods_compare.md", help="Final comparison report path.")
    parser.add_argument("--final-answer-config", help="Optional JSON config for final answer detection.")
    parser.add_argument("--final-answer-item", action="append", help="Business-specific final answer key:value pattern.")
    parser.add_argument("--llm-max-samples", type=int, default=30)
    parser.add_argument("--llm-max-prompt-chars", type=int, default=60000)
    parser.add_argument("--llm-max-trace-chars", type=int, default=2000)
    parser.add_argument("--llm-max-dynamic-fields", type=int, default=80)
    return parser


def main(argv: List[str] | None = None) -> None:
    args = build_parser().parse_args(argv)
    prepare_agent_llm_tasks(args)


if __name__ == "__main__":
    main()
